# Generated by Django 4.2.7 on 2023-12-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250000000000000000)),
                ('message', models.TextField(max_length=25000000000000000000)),
                ('date', models.DateTimeField()),
                ('image', models.CharField(max_length=2500000000000000000000000000000)),
            ],
        ),
    ]
